[유저] jwt 필터 구현
realSolarDragons/back-end pull request #145
Opened 2023-06-06 09:22 UTC by solpinetree

* [JwtTokenGenerator : 어노테이션 통해서 빈등록 하도록 수정](https://github.com/realSolarDragons/back-end/commit/374777d292d0196957f92b433eed41dc85729d55)
     *  기존에 `SecurityConfig.class` 에서 빈 등록을 했었는데, 그 클래스가 다른 용도로 쓰여야 하므로 코드를 수정했습니다

* [jwt token filter 구현](https://github.com/realSolarDragons/back-end/commit/58179d31c6c6073e3500032f82ff65bd7732af3b)
     * securityContext에 넣을 userDto 를 정의했습니다
     * jwtTokenFilter에서 token에 담긴 userId도 검증해야하지만 지금은 검증하지 않도록 했습니다. securityContext 에 담기는 것은 User 엔티티가 아니라 UserDto 이므로 서비스단에서 요청을 처리하기 위해 DB 에 접근해서 User 엔티티를 가져와야합니다. 이렇게 token 검증 + 요청 처리 -> 총 2번의 DB 접근이 있기 때문에 token 검증 할 때는 redis와 같은 캐시를 쓰는 것으로 알고 있습니다. 지금은 개발 단계이고 db 접근을 최소화하기 위해 검증하지 않고 바로 UserDto에 userId의 값만 넣어서 securityContext에 넣도록 설정했습니다. 
     * token 관련한 errorCode를 추가했습니다. 
     * ServiceType 에 `AUTHENTICATION` 값을 추가했습니다.

* [시큐리티 설정](https://github.com/realSolarDragons/back-end/commit/828b6a9bc8e68ccdc637a682dc12d34a93bda6db)
     * 로그인, 회원 가입 api는 token 없이도 접근할 수 있도록 설정했습니다
     * CustomAuthenticationEntryPoint를 구현했습니다. 인증 요청이 실패했을 때 CustomAuthenticationEntryPoint 가 호출됩니다. 안에서 실패 에러를 Response 틀을 맞춰서 반환하도록 설정했습니다.

* [개발 과정에서 테스트를 위한 토큰 발급 api 추가](https://github.com/realSolarDragons/back-end/commit/248992fabe28ec751d9e42ccc910b932cd19ce47)
     * PathVariable userId 를 id로 가지는 사용자의 token을 발급해서 해당 token을 이용해서 다른 api들을 테스트할 수 있도록 api를 추가했습니다.

* [api 를 요청한 유저의 id를 securityContext에서 추출하는 메소드 정의](https://github.com/realSolarDragons/back-end/commit/98ed58975df5ca8fac9013719087d6ed7ae80ffc)
     * `AbstractService` 에 `getCurrentUserId()` 라는 메소드를 정의했습니다. 이 메소드를 통해서 지금 api를 요청한 사용자의 id를 조회할 수 있습니다. 

* [token으로 추출한 userId를 사용하도록 서비스, 컨트롤러 코드 수정](https://github.com/realSolarDragons/back-end/commit/8696d1dca17ce5a8763a18b1feb398149fa6d3e3)
     * **잘못 수정할 수도 있어서 Blind관련 코드는 수정하지 않았습니다.  review 끝나면 변경해서 커밋해주시면 감사하겠습니다! 따로 이슈를 파서 적용시키셔도 됩니다**

추가로 얘기하고 싶었던 부분이 있었습니다!
* token 관련 처리를 하면서 `JwtTokenGenerator` 의 이름이 적합하지 않다고 생각이 들었습니다. 해당 클래스는 토큰을 생성하는 기능만 하는 것이 아니기 때문입니다. (token parsing, validate token 등). `JwtTokenUtil` 이라는 이름이 더 적합한 것 같다고 생각했는데, 어떻게 생각하시나요?

This closes #144

2023-06-09 09:01 UTC, YGwan requested changes
수고하셨습니다!!

제가 spring security을 잘 몰라 공부하는 과정때문에 리뷰 시간이 너무 길어졌네요... 죄송합니다!!

> token 관련 처리를 하면서 JwtTokenGenerator 의 이름이 적합하지 않다고 생각이 들었습니다. 해당 클래스는 토큰을 생성하는 기능만 하는 것이 아니기 때문입니다. (token parsing, validate token 등). JwtTokenUtil 이라는 이름이 더 적합한 것 같다고 생각했는데, 어떻게 생각하시나요?

이 부분 좋은것 같아요!! 이후 코드 수정할때 반영해주시면 감사하겠습니다!!

> 잘못 수정할 수도 있어서 Blind관련 코드는 수정하지 않았습니다. review 끝나면 변경해서 커밋해주시면 감사하겠습니다! 따로 이슈를 파서 적용시키셔도 됩니다

해당 작업이 끝난 후 제가 따로 이슈를 파서 바로 적용시키도록 하겠습니다.

많은 작업을 하셨더라구요!! 수고 많으셨습니다!!

2023-06-09 09:31 UTC, YGwan commented on src/main/java/com/ting/ting/util/JwtTokenGenerator.java
> +            Jwts.parserBuilder().setSigningKey(getKey()).build().parseClaimsJws(token).getBody();
> 해당 로직을 사용하기 위해서는 bearer 토큰 파싱 작업이 필요합니다!!
저같은 경우에는 bearer 토큰이 아니라는 가정하에 처리한 것이기 때문입니다!!

아 근데 지금 확인해보니 해당 부분이 없어도 에러 처리가 안나네요... ㅋㅋㅋ 있어도 안나구요!!
spring security가 알아서 처리해주나봐요!!

2023-06-09 09:34 UTC, solpinetree commented on src/main/java/com/ting/ting/dto/response/Response.java
> +    public String toStream() {
해당 에러가 인증과정에서 생기는 에러를 말씀하시는 거 맞나요?? 제가 이해를 잘 못하고 있는 것 같습니다. 혹시 문제가 생기는 상황이 어떤 것이고, 어떤 제대로된 에러가 발생하지 않는 건지 자세히 설명해주시면 감사하겠습니다!!

2023-06-09 11:55 UTC, solpinetree commented on src/main/java/com/ting/ting/configuration/SecurityConfig.java
> +                        .mvcMatchers("/ting/**").permitAll()
넵 알겠습니다 반영하겠습니다!

2023-06-09 11:58 UTC, solpinetree commented on src/main/java/com/ting/ting/util/JwtTokenGenerator.java
> +            Jwts.parserBuilder().setSigningKey(getKey()).build().parseClaimsJws(token).getBody();
> 추가적으로 filter 처리를 보니 isValidToken 해당 메서드의 반환값인 boolean 값이 쓰이지 않더라구요!!
> 해당 메서드를 void validateToken(String token)으로 바꾸시는건 어떠신가요??

네 저도 그게 나을 것 같습니다! 반영하겠습니다

2023-06-09 12:25 UTC, solpinetree commented on src/main/java/com/ting/ting/configuration/filter/JwtTokenFilter.java
> +    protected boolean shouldNotFilter(HttpServletRequest request) {
permitAll() 을 해도 필터를 타기 때문입니다!!

2023-06-09 12:26 UTC, solpinetree commented on src/main/java/com/ting/ting/domain/constant/UserRole.java
> +
별 다른 의미는 없었습니다 반영해서 다시 커밋하겠습니다!

2023-06-09 12:30 UTC, solpinetree commented on src/main/java/com/ting/ting/exception/CustomAuthenticationEntryPoint.java
> +    public void commence(HttpServletRequest request, HttpServletResponse response, AuthenticationException authException) throws IOException, ServletException {
제가 따로 추가한 것은 아니고 AuthenticationEntryPoint.commence 메소드를 그대로 오버라이딩한 것 입니다!!

2023-06-09 12:34 UTC, solpinetree commented on src/main/java/com/ting/ting/util/JwtTokenGenerator.java
>      public boolean isValidToken(String token) {
위와 중복되는 내용 말씀하시는 거 맞나요??

2023-06-09 14:51 UTC, YGwan commented on src/main/java/com/ting/ting/exception/CustomAuthenticationEntryPoint.java
> +    public void commence(HttpServletRequest request, HttpServletResponse response, AuthenticationException authException) throws IOException, ServletException {
아아 근데 메서드 보니 ServletException 제거해도 아무런 문제가 없더라구요!!
한번 확인해주시면 좋을것 같아요!!

2023-06-09 14:57 UTC, solpinetree commented on src/main/java/com/ting/ting/dto/response/Response.java
> +    public String toStream() {
아하 이해했습니다!! 에러 인 것을 알 수 있도록 수정하겠습니다!!!

2023-06-09 15:19 UTC, solpinetree commented on src/main/java/com/ting/ting/dto/response/Response.java
> +    public String toStream() {
> jwtTokenFilter에서 발생했던 에러를 request.setAttribute("exception") 에 담아뒀습니다
그걸 불러오는 코드입니다!
근데 지금 코드를 다시 보니 더 나은 방법이 생각나서 리팩토링 하고자 합니다!
일단, 지금은 이 상태로 커밋하고 따로 이슈를 파서 리팩토링 해도 될까요?

이것도 이 때 같이 수정해서 커밋해도 될까요?

2023-06-09 17:02 UTC, YGwan requested changes
> 추가적으로 filter 처리를 보니 isValidToken 해당 메서드의 반환값인 boolean 값이 쓰이지 않더라구요!!
해당 메서드를 void validateToken(String token)으로 바꾸시는건 어떠신가요??

이 부분 처리가 안된거 같아요!!

추가적으로 해당 클래스를 JwtTokenUtil로 변경하자고 말씀해주셨는데 해당 부분도 반영이 안된걸로 확인됩니다!!

2023-06-10 05:17 UTC, solpinetree commented on src/main/java/com/ting/ting/exception/CustomAuthenticationEntryPoint.java
> +        TingApplicationException e = (TingApplicationException)request.getAttribute("exception");
JwtTokenFilter 39번째 줄 확인 부탁드립니다!

2023-06-10 05:18 UTC, solpinetree commented
> 이 부분 처리가 안된거 같아요!!
추가적으로 해당 클래스를 JwtTokenUtil로 변경하자고 말씀해주셨는데 해당 부분도 반영이 안된걸로 확인됩니다!!

수정해서 커밋했습니다!

2023-06-10 05:27 UTC, YGwan commented on src/main/java/com/ting/ting/exception/CustomAuthenticationEntryPoint.java
> +        TingApplicationException e = (TingApplicationException)request.getAttribute("exception");
아 감사합니다!! 이런식의 처리가 생소해 제가 잘 접근을 못했네요ㅠㅠ

감사합니다!!

2023-06-10 05:28 UTC, YGwan approved these changes
수고하셨습니다!!

2023-06-10 07:14 UTC, merged