Feature/#3 searching user
realSolarDragons/back-end pull request #15
Opened 2023-04-26 08:57 UTC by YGwan

불필요한 띄어쓰기 수정하고 구현할때 Gender부분이 에러가 생겨 이 부분 수정하였습니다.
소개팅 사용자 조회같은경우 일단 전체 사용자를 조회할 수 있도록 구현하기로 했어서 그렇게 구현했습니다.
그런데, 사실 소개팅 사용자 조회할때 쓰이는 정보는 사용자들 전체 정보 중 일부분만을 사용합니다. 그런데 저같은 경우에는 일단은 전체 정보를 다 가져올 수 있도록 구현하였습니다. 이 부분을 일부분만 가져올 수 있게끔 구현하는게 좋을지 아니면 전체 정보를 다 가져오고 front 단에서 이 중 일부 정보만을 가져와 사용할 수 있게끔 구현하는 것이 좋을지에 대해서 어떻게 생각하시는지 궁금합니다!!

2023-04-26 09:03 UTC, solpinetree commented
혹시 #14 이 리팩토링 리뷰 먼저 해주실 수 있을까요?!
또한, user entity에서 유효성 검사 annotation은 한 줄로 쓰면 코드가 길어지지도 않고 가독성이 떨어지는 것도 아니라 
한 줄로 묶어서 코드를 작성했었습니다. 혹시, 띄어쓰는 걸 선호하시는 걸까요??

2023-04-28 02:24 UTC, solpinetree requested changes

2023-04-30 04:55 UTC, solpinetree approved these changes

2023-04-30 08:12 UTC, YGwan commented on src/main/java/com/ting/ting/service/UserService.java
> +        return userRepository.findAll();
좋은것 같습니다! 생각해보니 당연한거였네요 엔티티 자체를 가지고 처리하는것보단 요구하는 값들을 세분해서 리턴하는 형식이 더 좋은 꼴인것 같습니다!

2023-05-01 05:53 UTC, merged