[과팅] 메인페이지
realSolarDragons/back-end pull request #21
Opened 2023-04-28 16:46 UTC by solpinetree

* 과팅 팀 생성 기능 구현
* 과팅 팀 참가 관련 기능 기능 구현
     *  모든 팀 조회, 팀 참가 요청 기능, 팀 참가 취소 기능
* 사용자가 속한 팀 조회 기능
을 구현했습니다.  

더미 데이터로 로직을 구현하고 확인하는 과정이기 때문에 코드 상에서 유저 아이디나 과팅 아이디를 임의로 설정해서 select 하는 부분이 있습니다

This closes #6

2023-04-30 15:39 UTC, YGwan requested changes
전체적으로 너무 잘해주셨습니다!!
어우... 저보다 너무 잘하셔서 많이 배우고 있고 따라가기도 벅찹니다.. ㅎㅎ

혹시 요청 처리와 그룹 생성 관련해서 @ManyToMany관계를 사용하셨더라구요
요즘 추세가 @ManyToMany를 잘 사용 안하기도 하고 실무에서는 더더욱 필수적인 상황이 아니면 잘 사용 안한다구 하더라구요! 꼭 필요하면 @ManyToOne & @OneToMany로 처리한다든지 이렇게 처리하는게 일반적이라고 하더라구요!

혹시 @ManyToMany를 사용하신 이유가 있을까요?? 저같은 경우에는 요청 처리를 @ManyToOne을 통해서 했는데 얘기해보고 둘 중 하나를 선택하는게 더 좋을것 같아서요!! (물론 제가 제대로 잘 동작하게 했는지는 잘 모르겠지만...)

확실히 코드를 보면서 spring을 많이 해보신 느낌이 났습니다. 제가 더 열심히 노력하도록 하겠습니다!!
수고 많으셨어요!! 회의하면서 추가적으로 코드 설명이 필요한 부분을 요청드리도록 하겠습니다!

2023-04-30 15:39 UTC, YGwan commented on src/main/java/com/ting/ting/controller/GroupController.java
> +
혹시 줄 두칸을 띄우신 이유가 있을까요??

2023-04-30 15:39 UTC, YGwan commented on src/main/java/com/ting/ting/controller/GroupController.java
> +    public Page<GroupResponse> list(Pageable pageable) {
해당 메서드가 어떤 리스트인지 list라는 함수명만 가지고는 알기가 힘들거 같아요
후에 들어갈 팀, 상대 팀 등의 추가적인 로직이 들어가면 구분하기 위해서 함수명을 좀 더 확실하게 명시해주는건 어떨까요?
(예를 들어 들어갈 팀이니깐 groupsToJoinList)

2023-04-30 15:39 UTC, YGwan commented on src/main/java/com/ting/ting/controller/GroupController.java
> +    public List<GroupResponse> mylist() {
메서드명 확인해주세요!!

2023-04-30 15:39 UTC, YGwan commented on src/main/java/com/ting/ting/controller/GroupController.java
> +    public String create(@RequestBody GroupRequest request) {
저는 개인적으로 String을 리턴할때는 String보다는 ResponseEntity<String> 을 좀 더 선호합니다!
ResponseEntity<String> 를 사용하면 해당 클래스가 가진 메서드도 사용할 수 있고 success를 출력한다는게 확실하게 보이니깐요!!
단순히 String을 리턴하면 해당 리턴값이 view파일인지 String인지 추가적으로 확인해야하는 경우가 생길 수 있으니깐요!!
혹시 선호하는 스타일이 있으신지 궁금합니다!

2023-04-30 15:39 UTC, YGwan commented on src/main/java/com/ting/ting/domain/Group.java
> +    public static Group of(User leader, String groupName, Gender gender, String school, int numOfMember, String memo) {
이렇게 static 메서드로 처리하는거 정말 좋은거 같습니다!!
많이 배우고 있습니다!!

2023-04-30 15:39 UTC, YGwan commented on src/main/java/com/ting/ting/service/GroupService.java
> +    public void createJoinRequest(long groupId) {
해당 요청의 경우 만약 팀에 정해진 인원이 꽉 차있으면 추가적으로 처리하는 로직을 추가하시는건 어떠신가요??
예를들어 팀원이 꽉 차있는지 확인해서 꽉차있으면 에러를 발생시키거나 메세지를 보낸다던지 이런식으로 처리하는것도 좋을 것 같습니다!!

2023-05-01 07:27 UTC, solpinetree commented
> 전체적으로 너무 잘해주셨습니다!! 어우... 저보다 너무 잘하셔서 많이 배우고 있고 따라가기도 벅찹니다.. ㅎㅎ
> 
> 혹시 요청 처리와 그룹 생성 관련해서 @manytomany관계를 사용하셨더라구요 요즘 추세가 @manytomany를 잘 사용 안하기도 하고 실무에서는 더더욱 필수적인 상황이 아니면 잘 사용 안한다구 하더라구요! 꼭 필요하면 @manytoone & @OneToMany로 처리한다든지 이렇게 처리하는게 일반적이라고 하더라구요!
> 
> 혹시 @manytomany를 사용하신 이유가 있을까요?? 저같은 경우에는 요청 처리를 @manytoone을 통해서 했는데 얘기해보고 둘 중 하나를 선택하는게 더 좋을것 같아서요!! (물론 제가 제대로 잘 동작하게 했는지는 잘 모르겠지만...)
> 
> 확실히 코드를 보면서 spring을 많이 해보신 느낌이 났습니다. 제가 더 열심히 노력하도록 하겠습니다!! 수고 많으셨어요!! 회의하면서 추가적으로 코드 설명이 필요한 부분을 요청드리도록 하겠습니다!

실무에서는 `@ManyToMany` 를 잘 안 사용한다고 하는 그 이유가
     1. 매핑되는 관계의 id들 외에는 추가 정보를 저장할 수 없다. 
     2. 세밀한 쿼리를 시행하기 어렵다.
     3. 독립적으로 generated 되는 대리키 사용을  권장한다. 
라고 생각합니다.

2,3 번은 아직 실감할 수 없어서 1번을 중점으로 고민했습니다.

그래서  `@ManyToMany` 를 사용한 이유는 `팀 가입 요청`에 member 정보와 팀 정보만 들어간다고 판단해서였는데요. `RequestStatus` 를 포함할 생각을 못했습니다! 결론적으로는 추가 정보(`RequestStatus`)가 테이블에 포함되어야 하니까 `@ManyToOne` & `@OneToMany` 로 바꾸는 게 맞는 것 같습니다. 
 팀 멤버 정보를 가지고 있는 Group.members 같은 경우에도 팀장이 초대한 멤버인 경우에 따라 `RequestStatus` 가 필요하다고 생각이 되었습니다.  그래서 Group.members 같은 경우도 `@ManyToOne` & `@OneToMany` 로 변경하는 게 맞는 것 같습니다!

코딩이 간결해지는 이점과 기회 비용을 비교하고자 한 번 사용해봤던 거 였는데, 고민해보니 다대일, 일대다로 풀어도 그렇게까지 코딩이 복잡해지는 것 같지 않습니다. 이외에도, 확장성 측면에서도 고민해봤을 때 앞으로도 `@ManyToMany`보다 일대다, 다대일로 푸는 게 나을 것 같습니다! 

이 부분 수정해서 커밋하겠습니다! 리뷰 감사합니다 ㅎㅎㅎ

2023-05-01 22:18 UTC, solpinetree commented
f7b397f28902e631f08bb8d34474fb26a01bd9b4
-> conflict resolve 한 커밋입니다.

2023-05-02 04:50 UTC, YGwan reviewed
고치느라 수고하셨어요...
역시 잘 짜시는군요!!
중간중간 주석을 달아주셔서 보기 정말 편했어요!!
배려 감사드립니다 ㅎㅎ

수고하셨습니다!!

2023-05-02 04:50 UTC, YGwan commented on src/main/java/com/ting/ting/service/GroupService.java
> +            throw new RuntimeException("gender does not match");
에러를 혹시 RuntimeException으로 잡으신 이유가 있을까요??
GroupException 클래스를 만들고 이걸로 에러를 생성하면 서버측 로그에 이게 과팅 관련 오류이다를 좀 더 잘 표현할 수 있을거 같다는 생각이 들었어요!
추가적으로 이러한 에러는 사용자측에는 보여주면 안된다고 생각해 후에 Controller에서 잡아야되는대 RuntimeException은 너무 큰 범위라는 생각이 들었습니다!
어떻게 생각하시는지 궁금합니다.

2023-05-02 04:50 UTC, YGwan commented on src/main/java/com/ting/ting/service/GroupService.java
> +        groupMemberRequestRepository.findByGroupAndUser(group, user).ifPresent(it -> {
오 저는 원래 findBy로 처리하는걸 좋아했는데 예전 코드에서는 주로 referenceById를 사용하셧더라구요.
이 부분 얘기해보려구 했는데 이번 코드에서는 findBy를 많이 쓰셧군요!!
좋습니다!!

2023-05-02 04:50 UTC, YGwan commented on src/main/java/com/ting/ting/service/GroupService.java
> +        User user = loadUserByUserId(userId);
여기서의 user는 결국 leader를 나타내는 거군요!!
아래 toEntity의 매개변수로 leader를 나타내주셨긴하지만 해당 함수에서 변수명을 명시적으로 나타내주는게 어떨까요?
그렇게 되면 해당 유저 정보가 leader로 사용되는 정보구나를 toEntity함수를 보지 않고도 이 함수내에서 바로 알 수 있을거 같아서 더 좋을거 같다고 생각했어요!

2023-05-02 06:07 UTC, solpinetree commented on src/main/java/com/ting/ting/service/GroupService.java
> +    public void createJoinRequest(long groupId) {
test

2023-05-02 06:12 UTC, YGwan commented on src/main/java/com/ting/ting/controller/GroupController.java
> +    public String create(@RequestBody GroupRequest request) {
오 좋은거 같아요!! 저도 이러한 형식으로 다음부터 작성하겠습니다.
custom ResponseEntity는 후에 맞춰서 정해요!!

2023-05-02 06:12 UTC, YGwan approved these changes
수고하셨습니다!!

2023-05-02 06:22 UTC, merged