Feature/#5 blind request remove
realSolarDragons/back-end pull request #23
Opened 2023-04-29 17:49 UTC by YGwan

2023-04-30 05:14 UTC, solpinetree requested changes

2023-04-30 05:14 UTC, solpinetree commented on src/main/java/com/ting/ting/domain/User.java
> +    @NotNull @Size(max = 1)
이 부분은 제가 작성했던 코드였는데요!
과팅 부분에서 확인해본 결과 enum type에는 javax.validation `@Size` 어노테이션이 에러가 남을 확인했습니다.
data.sql 에서는 디비에 직접 insert 하기 때문에 javax.validation을 타지 않아서 에러가 안 났던 것 같습니다. 
따라서 @Size 어노테이션은 삭제가 필요합니다.

2023-04-30 05:14 UTC, solpinetree commented on src/main/java/com/ting/ting/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
`@Repository` 어노테이션을 따로 사용하신 이유가 있으실까요??
있다면, 기존에는 `@Repository` 가 없는 방법으로 작성했어서 스타일을 맞추려고 합니다!!

2023-04-30 05:14 UTC, solpinetree commented on src/main/java/com/ting/ting/service/BlindRequestService.java
> +        if (fromUser.equals(toUser)) {
값을 불러오기 전에 equals( 같은 유저인지 비교) 를 하면 디비에 access하기 전에 request deny 를 할 수 있어서 
더 좋을 거라고 생각됩니다. 어떻게 생각하시나요??

2023-04-30 05:14 UTC, solpinetree commented on src/main/java/com/ting/ting/service/UserService.java
> +    public List<BlindUsersInfoResponse> usersInfo() {
지금 단계에선 크게 상관이 없지만, 후에 `pagination`을 도입했을 경우에는 List보다는`Page`로 반환하는 게 좋을 것 같다고 생각합니다! 혹시 List로 반환하고 후에 다른 로직을 통해 pagination을 도입하실 생각이셨는지 궁금합니다!

2023-04-30 07:24 UTC, YGwan commented on src/main/java/com/ting/ting/controller/BlindDateController.java
> +    @ExceptionHandler(UserException.class)
네넵 일단 이 단계에서는 이렇게 처리했습니다!! 이후에 에러 처리 작업은 같이 고민해서 맞춰보면 좋을거 같아요!!

2023-04-30 07:25 UTC, YGwan commented on src/main/java/com/ting/ting/domain/User.java
> +    @NotNull @Size(max = 1)
아 저같은 경우에는 User부분을 추가적으로 건든 부분이 없어서 이후에 merge과정에서 분명 충돌이 생길텐대 그때 User부분은 누나가 하신 부분으로 맞춰서 하면 될 것 같습니다!!

2023-04-30 08:08 UTC, YGwan commented on src/main/java/com/ting/ting/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
아 저같은 경우 @Component, @Controller와 같이 스프링이 시작할때 @ComponentScan에 의해 스프링 빈에 등록하기 위해서 사용했습니다.
근데 지금 보니 @Repository를 안써도 해당 클래스가 interface를 상속받았기때문에 자동으로 스프링 빈에 등록되는군요.
그럼 제가 스타일을 맞춰 해당 어노테이션을 제거하도록 하겠습니다!

2023-04-30 08:10 UTC, YGwan commented on src/main/java/com/ting/ting/service/BlindRequestService.java
> +        if (fromUser.equals(toUser)) {
아 그게 헐씬 좋은거 같습니다!! 해당 부분을 dto에서 처리하도록 수정해서 구현하도록 하겠습니다!

2023-04-30 08:11 UTC, YGwan commented on src/main/java/com/ting/ting/service/UserService.java
> +    public List<BlindUsersInfoResponse> usersInfo() {
아 네넵!! 이 부분 커밋해주신 코드에서 확인했습니다! 이 부분 수정해서 올리도록 하겠습니다!

2023-05-01 08:02 UTC, solpinetree requested changes

2023-05-01 08:02 UTC, solpinetree commented on src/main/java/com/ting/ting/domain/constant/RequestStatus.java
> +    P("요청중"),
RequestStatus 에서 `P`, `S`, `R` 이 무엇을 의미하는지 유추가 힘든 것 같습니다

P -> PENDING
S -> ACCEPTED
R -> REJECTED

로 풀어서 쓰는 건 어떨까요??

이에 대해 고민하던 중, `Gender` enum에 대해서도 다시 생각해보게 되었는데
저는 M, W 이 직관적이라고 생각했는데 이 또한 주관적일 수 있다는 생각을 했습니다
M -> MEN
W -> WOMEN 
으로 바꾸는 게 나을까요? 어떻게 생각하시는지 궁금합니다!

2023-05-01 08:57 UTC, YGwan commented on src/main/java/com/ting/ting/service/UserService.java
> +    public List<BlindUsersInfoResponse> menUsersInfo(Pageable pageable) {
아 테스트할때는 별로 문제가 되지 않앗는대 확인해보니 Page로 리턴을 할 필요가 있겠네요!!
해당 부분 Page<BlindUSersInfoResponse>로 수정하였습니다.

추가로, 과팅 코드를 보니 public static from 메서드를 사용해서 리턴 타입을 변경하는 방식을 사용하시더라구요!!
이 부분 스타일 맞춰서 변경하였습니다.

2023-05-01 09:00 UTC, YGwan commented on src/main/java/com/ting/ting/domain/constant/RequestStatus.java
> +    P("요청중"),
"RequestStatus 에서 P, S, R 이 무엇을 의미하는지 유추가 힘든 것 같습니다" 이 부분은 저도 동의합니다!! 그래서 이 부분은 바꾸도록 하겠습니다!! 저도 이 부분 고민을 좀 했었는데 확실히 P, S, R로는 확실하게 구분하기가 힘든것 같아 이 부분은 풀어쓰는게 더 좋다고 생각합니다.

M, W같은경우는 저는 선호하는 바가 없습니다!! 혹시라도 선호하는 바가 있으시면 말씀해주시면 감사하겠습니다!!

2023-05-01 13:13 UTC, solpinetree commented on src/main/java/com/ting/ting/domain/constant/RequestStatus.java
> +    P("요청중"),
일관성 있게 MEN, WOMEN 으로 바꾸는 게 나을 것 같습니다!

이 파트는 이번에 소개팅, 과팅 다 main branch에 머지한 후 바꾸는 게 나을 것 같습니다!

2023-05-01 13:15 UTC, solpinetree approved these changes
수정사항 잘 반영해주셔서 감사합니다! 고생하셨습니다 👍👍👍

2023-05-01 13:17 UTC, solpinetree commented
a696cabc7633a6ea0a3e82463577a6c751907d24
-> data.sql 에서 conflict 있다고 해서 resolve 한 커밋입니다.

2023-05-02 05:50 UTC, merged