[custom exception] 구현
realSolarDragons/back-end pull request #44
Opened 2023-05-04 07:01 UTC by YGwan

custom exception 구현 완료했습니다.

ErrorCode와 ServiceType 이렇게 두가지의 enum을 추가했습니다.
ErrorCode에서는 에러 정의 및 에러 메세지를 갖고 잇는 enum 클래스입니다.
ServiceType의 경우 저희의 서비스인 소개팅, 과팅을 정의한 enum 클래스입니다.
에러가 생겻을 경우 로그에서 어떤 부분의 서비스에서 에러가 발생한지 알면 더 좋을 것 같아 명시해주기 위해 사용하였습니다.

에러 메세지는
[USER_NOT_FOUND :: BLIND] : [0]의 유저 정보가 존재하지 않습니다.
이런식으로 작동하도록 구현하였습니다.

감사합니다.

2023-05-05 05:40 UTC, solpinetree requested changes

2023-05-05 07:08 UTC, solpinetree requested changes

2023-05-05 07:08 UTC, solpinetree commented on src/main/java/com/ting/ting/exception/TingApplicationException.java
> +public class TingApplicationException extends IllegalArgumentException {
여기서 RuntimeException이 아닌 IllegalArgumentException을 상속받으신 이유가 있으실까요?!

IllegalArgument를 상속받는 것은 `TingApplicationException` 이 처리할 다른 NPE 나 ClassCastException 등등은 받지 않는다고 오해할 수도 있지 않을까요?? 
이런 이유로 보통 custom exception을 구현할 때 `RuntimeException`을 상속받는 것으로 알고있습니다!

2023-05-05 15:27 UTC, YGwan commented on src/main/java/com/ting/ting/controller/BlindDateController.java
> +    @ExceptionHandler(TingApplicationException.class)
아 원래는 Controller마다 역할이 나눠져 있기 때문에 해당 클래스의 에러는 해당 클래스에서 처리하는게 더 좋을것 같아서 이런식으로 구현했었습니다. 또한 Global하게 일단 잡고, 추가적으로 좀 더 깊이 있게 잡기 위해서 ( 예외 처리 로직을 좀 다르게 하고 싶다면 ) 이런식으로 클래스의 Handler를 통해 에러를 잡을 수 있도록 구현하기 위해서 이런식의 방법을 선호했습니다.

예를 들어, BlindDate에서 에러가 발생했을 경우 `@ResControllerAdvice`과 BlindDateController에 둘 다 에러를 잡는 코드가 있다면 더 밀접한 BlindDateController 에러 잡는 코드가 실행되기 때문에 이런식으로 둘 다 구현하는 방식을 주로 했습니다.

하지만 지금 같은 경우 전역적으로 잡는게 더 좋다고 생각했습니다. 애초에 Enum 클래스로 어디서 에러가 발생했는지 명시해 줄 뿐더러, 에러 처리 로직이 다른 경우가 아직까진 없기 때문에 전역적으로 `@RestControllerAdvice` 를 통해 에러를 잡는 방식으로 변경하도록 하겠습니다!! 그렇게 되면 말씀하신대로 중복 코드 제거 및 일관성 유지, 예외 처리 확장성에도 좋을 것 같기 때문입니다.

수정해서 반영하도록 하겠습니다!

2023-05-05 15:44 UTC, solpinetree commented on src/main/java/com/ting/ting/exception/TingApplicationException.java
> +public class TingApplicationException extends IllegalArgumentException {
엇.. `IllegalArgumentException` 도 `RuntimeException` 을 상속받는 unchecked exception 아닌가요??

추가적으로 관련 좋은 정보 첨부합니다!
* https://stackoverflow.com/questions/52983402/why-does-spring-prefer-unchecked-exceptions

2023-05-05 16:12 UTC, YGwan commented on src/main/java/com/ting/ting/exception/TingApplicationException.java
> +public class TingApplicationException extends IllegalArgumentException {
아 맞습니다!! `IllegalArgumentException` 는 `RuntimeException`의 하위 클래스라 unchecked 예외가 맞습니다!! 제가 잘못 말했네요!! 죄송합니다...
위의 말을 수정하자면 저는 IllegalArgumentException을 제외한 다른 에러는 NPE나 다른 에러는 주로 GlobalControllerException에서 잡는 방식을 사용했어서 이런식으로 구현했었습니다. 
Exception을 만들때 대부분 RuntimeException이나 IllegalArgumentException을 주로 사용하는걸로 알고 있는대 RuntimeException은 너무 범위가 크고 명시적으로 IllegalArgumentException이 "부적절한 인자값으로 인한 제외" 이기 때문에 더 적절하다고 생각해서 였습니다!!

하지만 자료를 추가적으로 확인해보니 custom Exception은 주로 RuntimeException을 사용하기도 하고 말씀대로 `TingApplicationException`이 다른 에러에 대한 처리는 안한다고 생각할 수도 있다고 생각합니다!!
해당 부분 수정하도록 하겠습니다.
감사합니다!!

2023-05-05 21:56 UTC, solpinetree commented on src/main/java/com/ting/ting/exception/TingApplicationException.java
> +    private ServiceType serviceType;
serviceType 명시해주는 거 정말 좋은 것 같습니다! 👍👍

2023-05-05 21:56 UTC, solpinetree commented on src/main/java/com/ting/ting/exception/ErrorCode.java
> +    USER_NOT_FOUND("User is not founded"),
Errorcode에 FE가 에러라고 인지할 수 있는 int형 코드나 HTTP STATUS 를 포함시켜서 해당 에러가 어떤 status를 가지는지
알려주는 것은 어떨까요??

원래 에러가 발생하면 FE는 400대, 500대의 request status를 받고 에러가 발생했음을 알게되는 것으로 알고 있습니다.
하지만, exception을 custom response에 담아서 보내게 되면 에러의 내용을 포함했든, 성공 데이터를 포함했든, 200대의 request status 가 반환됩니다. 그래서 기존의 request status를 대체할 또 다른 status가 errorCode에 포함되어야 한다고 생각합니다.

다른 방법이 있을지 혹은 어떻게 생각하시는지 궁금합니다!

2023-05-06 02:36 UTC, YGwan commented on src/main/java/com/ting/ting/exception/ErrorCode.java
> +    USER_NOT_FOUND("User is not founded"),
제가 custom response가 어떤식으로 동작하는지 잘 몰라서 이해가 잘 안되는것 같은대
예전에 하신 코드를 보니 custom response를 사용해도 결국 에러 처리는 ControllerAdvice에 있는 @ExceptionHandler가 처리하고 여기서 custom response또한 결국 ResponseEntity<?> 이런 식으로 동작하기 때문에 ResponseEntity.badRequest()로 처리하면 되는 것 아닌지 궁금합니다!!
혹시 제가 잘못 접근하고 있을 수도 있으니 그렇다면 알려주시면 감사하겠습니다!

2023-05-06 10:01 UTC, solpinetree commented on src/main/java/com/ting/ting/exception/ErrorCode.java
> +    USER_NOT_FOUND("User is not founded"),
@ExceptionHandler에서 에러를 받은 후에 ResponseEntity 로 반환값을 줄수도 있고, Custom Response로 반환값을 줄 수도 있어요! 이번 프로젝트에선 Custom Response로 반환값을 주려고 합니다.
 
하지만, 이와 상관 없이 ResponseEntity.badRequest()로 반환한다고 해도 badRequest는 400 request status 만 반환하기 때문에, FE에서는 어떤 에러인지 세분화해서 구분할 수 없을 거라고 생각합니다! 예를 들어, 서버에서 컨트롤하지 못한 에러가 던져진 경우(`@ExceptionHandler(RuntimeException.class)) internal_server_error를 던져야 하는데, 이를 bad requeset로 던지면 클라이언트 쪽에서는 internal error인지 client input error 인지 알 수 없으므로 ResponseEntity로 반환한다고 해도 Http status code나 FE와 상의된 request status code 를 도입해야한다고 생각합니다!

400대 에러와 500대 에러를 구분할 수 있다는 점 외에도 400대 에러(client error) 중에서도 어떤 client error인지 세분화해서 알려줄 수 있습니다.

이에 대해 어떻게 생각하지는지 궁금합니다!

2023-05-06 10:08 UTC, solpinetree commented on src/main/java/com/ting/ting/exception/ErrorCode.java
> +    USER_NOT_FOUND("User is not founded"),
@ExceptionHandler에서 에러를 받은 후에 ResponseEntity 로 반환값을 줄수도 있고, Custom Response로 반환값을 줄 수도 있어요! 이번 프로젝트에선 Custom Response로 반환값을 주려고 합니다.

하지만, 이와 상관 없이 ResponseEntity.badRequest()로 반환한다고 해도 badRequest는 400 request status 만 반환하기 때문에, FE에서는 어떤 에러인지 세분화해서 구분할 수 없을 거라고 생각합니다! 예를 들어, 서버에서 컨트롤하지 못한 에러가 던져진 경우(`@ExceptionHandler(RuntimeException.class)) internal_server_error를 던져야 하는데, 이를 bad requeset로 던지면 클라이언트 쪽에서는 internal error인지 client input error 인지 알 수 없지 않을까요?? 따라서, ResponseEntity로 반환한다고 해도 Http status code나 FE와 상의된 request status code 를 도입해야한다고 생각합니다!

400대 에러와 500대 에러를 구분할 수 있다는 점 외에도 400대 에러(client error) 중에서도 어떤 client error인지 세분화해서 알려줄 수 있습니다.

이에 대해 어떻게 생각하지는지 궁금합니다!

2023-05-06 10:09 UTC, solpinetree reviewed
댓글 확인 부탁드립니다!

2023-05-06 10:55 UTC, YGwan commented on src/main/java/com/ting/ting/exception/ErrorCode.java
> +    USER_NOT_FOUND("User is not founded"),
아 처음에는 저도 HTTPSTATUS를 도입해서 처리했었습니다. 근데 보니깐 HttpStatus가 결국 message랑 동일한 느낌이 들어 해당 부분을 삭제했습니다!!
그런데 생각해보니 사용자에게 중요한 에러 메세지는 한번 필터링 해서 들어가야되지만 결국 상태 코드는 제대로 들어가는게 더 좋다고 생각해 해당 부분을 수정하도록 하겠습니다.
추가적으로 서버 에러와 사용자 에러는 각각 500대 400대이기 때문에 해당 에러는 다른 클래스를 통해 구현하려고 했었습니다!!
하지만 custom error 클래스에서 에러코드를 추가해 처리하면 불필요한 중복을 줄일 수 있을것 같아 해당 방식으로 수정하도록 하겠습니다.

2023-05-06 10:55 UTC, YGwan commented on src/main/java/com/ting/ting/exception/ErrorCode.java
> +    USER_NOT_FOUND("User is not founded"),
좋은 의견 감사드립니다!!

2023-05-06 11:06 UTC, YGwan commented
해당 부분 ErrorCode에 HttpStatus관련 필드 추가하였고 동시에 GlobalControllerAdvice에 해당 에러 코드까지 보내는 로직 추가하였습니다!!

2023-05-06 11:36 UTC, solpinetree approved these changes
수정 사항 잘 반영해주셔서 감사합니다!!
구현된 custom exception 포함한 custom response(#27) 마무리 작업하고 커밋하겠습니다!
고생하셨습니다!

2023-05-06 12:35 UTC, merged