Gender 처리 로직 변경
realSolarDragons/back-end pull request #49
Opened 2023-05-04 07:48 UTC by YGwan

2023-05-05 06:17 UTC, solpinetree reviewed
이슈 처리해주셔서 감사합니다!

2023-05-05 06:17 UTC, solpinetree commented on src/main/java/com/ting/ting/domain/Group.java
> +    @NotNull @Size(max = 5)
ENUM 타입에는 @Size 어노테이션을 쓸 수 없는 것으로 알고 있습니다!
제가 먼저, `User` 에서 @Size 어노테이션을 제거해서 헷갈리지 않도록 했어야했는데 
죄송합니다.  
해당 부분 수정해주실 수 있으실까요?

2023-05-06 02:38 UTC, YGwan commented on src/main/java/com/ting/ting/domain/Group.java
> +    @NotNull @Size(max = 5)
아 네넵!! 수정 바로 하겠습니다!!
저도 Column 쪽에서 length를 통해 값을 처리하는대 동일한 코드인거 같아 확인해봣는대
실행 상 문제가 없길래 체크 레벨이 다른 줄 알았습니다!
수정해서 반영하도록 하겠습니다!

2023-05-06 10:12 UTC, solpinetree requested changes

2023-05-06 10:12 UTC, solpinetree commented on src/main/java/com/ting/ting/domain/Group.java
> +    @NotNull @Size(max = 5)
넵! 감사합니다!! `User` 에서 @Size 어노테이션이 에러가 안 난 이유는 `data.sql`에서 DB에 직접 접근해서 insert 하는 것이기 때문에 javax.validation을 타지 않아 에러가 발생하지 않습니다. 하지만 `Group` 을 Jpa를 통해 저장하면 에러가 발생함을 확인할 수 있습니다.

감사합니다

2023-05-06 10:23 UTC, YGwan commented on src/main/java/com/ting/ting/domain/Group.java
> +    @NotNull @Size(max = 5)
혹 어짜피 해당 클래스의 경우 Enum 타입이기 때문에 Gender에 속해 있는 값인 MEN, WOMEN이 아니면 후에는 에러를 발생시키도록 코드를 짤텐대 해당 컬럼에 길이 제한이 있을 필요가 있을까요??

2023-05-06 10:44 UTC, solpinetree commented on src/main/java/com/ting/ting/domain/Group.java
> +    @NotNull @Size(max = 5)
jpa를 통해서 저장하는 경우에는 필요 없을 것 같습니다! 다만, db에 접근해서 저장하는 경우의 측면에서는 MEN, WOMEN인지 확인할 방법이 없어 최소한의 장치를 쓰는 거라고 생각이 들기도 합니다. (mysql enum type이 있긴 하지만, mysql enum type의 사용은 권장하지 않는다고 합니다)

db에 접근해서 저장하는 경우는 아예 없어야 하는 게 맞지만, 이런 경우를 아예 제외 시키는 게 나을까요??

2023-05-06 10:52 UTC, YGwan commented on src/main/java/com/ting/ting/domain/Group.java
> +    @NotNull @Size(max = 5)
아 신중한게 좋기 때문에 처리하는게 좋을거 같습니다!! 근데 길이가 3 or 5이기 때문에 5로 처리하는게 좀 애매하다는 생각이 들어서 여쭤봣었습니다!! 기존 방식대로 처리하는게 좋을거 같아요!!

2023-05-06 11:29 UTC, solpinetree approved these changes
고생하셨습니다! 감사합니다

2023-05-06 12:32 UTC, merged