Custom Response 구현
realSolarDragons/back-end pull request #51
Opened 2023-05-06 18:18 UTC by solpinetree

* `ServiceType` 위치 변경 ( service 패키지 하위 -> exception 패키지 하위)
     지금 상황에서는 `ServiceType`을 exception을 처리할 때만 사용하므로 위치를 exception 패키지 밑으로 옮겼습니다. service 패키지와 controller 패키지 하위에는 관련 코드만(상수가 아닌) 있는 게 익숙한 저의 주관적인 의견일 수도 있습니다. 해당 변경점에 대해서 기호가 있으시다면 다시 바꿔도 무방합니다!! 기호가 있으시다면 알려주세요

* `GlobalControllerAdvice` 위치 변경( controller 패키지 하위 -> exception 패키지 하위)
     exception에 대한 기능을 하므로 exception 패키지 하위에 있는 것이 맞다고 판단했습니다!

---
## 구현 결과
* 성공시
![image](https://user-images.githubusercontent.com/83967710/236639731-df5065ba-c823-46ca-a54b-7152bfa8b01b.png)
* 실패시
![image](https://user-images.githubusercontent.com/83967710/236639754-6a766f57-34dd-4758-8068-cfc71ee7a5bc.png)

위와 같이 구현하고 보니 에러를 던지는 경우에 
resultCode와 serviceType의 정보가 message안에 한 번 더 언급이 되는 중복되는 꼴이라고 느껴졌습니다. 오히려 서버 로그에 더 적합한 message라고 생각되었습니다.
이에 기존의 getMessage() 함수는 서버 로그를 위한 함수로 변경하고, client에는 serviceType과 errorCode의 정보가 없는 개발자가 설정한 message만을 넘기도록 변경했습니다.
이렇게 변경하면,

![image](https://user-images.githubusercontent.com/83967710/236639943-51973df6-7f5a-4e50-8788-0074db918e7b.png)

위와 같이 message가 수정됩니다. 

클래스 위치 변경과 exception 메세지 변경 부분은 논의 후에 pr에 포함시켜야 했는데, 시간이 촉박하다 느껴져 일단 Pr로 세세히 설명 드린 후 논의 후에 논의 결과를 merge 시키는 방법으로 하는 게 낫다고 생각했습니다 ㅠㅠ 죄송합니다..ㅠㅠ
그러므로 이 pr은 논의 후에 변경될 여지가 큼을 알려드립니다. 클래스 위치 변경와 exception message 변경점에 대한 의견을 편하게 알려주시면 감사하겠습니다!

감사합니다

2023-05-06 19:21 UTC, YGwan requested changes
전반적으로 정말 고생하셨습니다.
말씀해주신 변경점은 저도 납득이 됐습니다. 자료를 살펴보니 클래스의 위치 변동은 이렇게도 많이 하더라구요!!
저는 기호가 없으니 이런식으로 하는게 좋을 것 같아요!!

추가적으로 Response 형식으로 인해 에러 메세지 출력 관련 변경점도 좋은것 같습니다. 해당 ServiceType 내용이 추가된다면 굳이 에러 메세지에도 추가할 필요가 없다고 생각합니다!

이러한 부분 혹여나 수정한다고 하시면 PR에다가 말씀해주셔도 좋습니다. 추가적으로 에러 처리 관련 부분 할때 Group 부분은 수정을 안했는데 죄송합니다... 다음부터는 이런 통합적인건 통합적으로 관리하도록 하겠습니다!!

수고하셨어요!!

2023-05-06 19:21 UTC, YGwan commented on src/main/java/com/ting/ting/exception/TingApplicationException.java
>      public String getMessage() {
확인해보니 해당 메서드가 사용되지 않는 것 같은대 해당 메서드를 삭제해도 되지 않을까요??
결국 getMessage가 하는 일을 getMessasgeForServer 메서드가 하는 것이라고 생각돼 사용할 일이 없을 것 같다는 생각이 들었습니다.

2023-05-06 19:21 UTC, YGwan commented on src/main/java/com/ting/ting/exception/TingApplicationException.java
>      public HttpStatus getHttpStatus() {
이것 또한 위와 같은 전개로 value처리로 아에 리턴하게끔 바꾸면 더 좋을 것 같네요!!

2023-05-06 19:21 UTC, YGwan commented on src/main/resources/application.yml
> +  sql.init.mode: never
혹시 추가하고 변경하신 윗 부분이 어떠한 이유로 추가했는지 알 수 있을까요??

2023-05-06 19:21 UTC, YGwan commented on src/main/java/com/ting/ting/exception/TingApplicationException.java
>      public String getMessage() {
혹시 "이에 기존의 getMessage() 함수는 서버 로그를 위한 함수로 변경하고" 라는 말씀이 혹시 해당 getMessage 메서드가 이후에 필요하다는 것을 의미하는 건가요??

2023-05-07 02:36 UTC, solpinetree commented on src/main/java/com/ting/ting/exception/ErrorCode.java
>      private final String message;
아 네 그렇네요! 그렇게 수정하는 게 나을 것 같습니다!! 수정해서 커밋하겠습니다

2023-05-07 03:00 UTC, solpinetree commented on src/main/java/com/ting/ting/dto/response/Response.java
> +    private ResultObject result;
크게 고민을 안했는데 result 멤버변수의 경우 setter가 열려있지 않고, 초기화하는 생성자가 있으므로 final 이 들어가도 될 것 같습니다!
해당 부분 수정해서 커밋하겠습니다.

2023-05-07 03:06 UTC, solpinetree commented on src/main/java/com/ting/ting/dto/response/ResultObject.java
> +        return new ResultObject(HttpStatus.OK.value(), null, "success");
네! 저도 그 부분을 고민했었는데요. 소통에는 별 상관이 없을 것 같습니다. FE의 경우 성공 request status 가 온 경우, `serviceType` 값을 읽을 필요가 없기 때문에 불필요한 정보를 주는 것이 아닌가 싶어서 따로 설정하지 않았습니다! 

하지만, 다시 생각해보니 serviceType을 null 값으로 주는 건 해당하는 서비스가 null 인지 오해를 불러일으킬 수도 있을 것 같아 명시적으로 값을 넘기는 게 나을 것 같습니다! 해당 부분 수정해서 커밋하겠습니다!

2023-05-07 03:11 UTC, YGwan commented on src/main/java/com/ting/ting/dto/response/ResultObject.java
> +        return new ResultObject(HttpStatus.OK.value(), null, "success");
마자요!! 제가 serviceType을 Enum으로 추가한 이유도 사실 FE측을 생각한거보다는 BE 에러 로그를 찍을때 좀 더 직관적으로 확인하기 위해 추가한거였습니다. 사실 FE는 소통할때 해당 부분을 알 필요가 없기 때문입니다!!
하지만 null을 주는건 말씀하신대로 오해를 불러 일으킬 수 있다고 생각합니다!!
그러면, 해당 서비스 타입은 에러 로그 메세지에만 추가하게 하고 response에는 보이지 않게 하는 방법도 좋을거 같아요!! 소통할때 필요 없다고 생각하시면 굳이 custom response에 추가를 안해도 될 것 같다는 생각이 들었습니다! 물론 직관적으로 보이게 하기 위해서는 추가하는 것도 좋다고 생각하구요!!
어떤걸 선호하시는지 궁금합니다 ㅎㅎ

2023-05-07 04:28 UTC, solpinetree commented on src/main/resources/application.yml
> +  sql.init.mode: never
ea35ba8eed131e2cfc57f060def28e0cb66a5140

커밋 메세지엔 포함 시켰는데 Pr message에는 포함시키는 걸 깜빡했네요! test시에 data.sql을 읽어오지 않도록 설정한 것입니다.

2023-05-07 04:30 UTC, solpinetree commented on src/main/java/com/ting/ting/exception/TingApplicationException.java
>      public HttpStatus getHttpStatus() {
넵! TingApplicationException에서는 httpstatus를 불러오기 보다는 errorCode에 접근해서 불러와도 되므로 해당 메서드는 필요없는 것 같습니다!

2023-05-07 04:31 UTC, solpinetree commented on src/main/java/com/ting/ting/exception/TingApplicationException.java
>      public String getMessage() {
개발자가 컨트롤하지 못한 에러를 `GlobalControllerAdvice` 에서 RuntimeException.class 로 받습니다. 
이 때, getMessage() 가 사용됩니다! 해당 코드 확인 부탁 드립니다.

2023-05-07 04:36 UTC, solpinetree commented on src/main/java/com/ting/ting/dto/response/Response.java
> +    public Response(TingApplicationException e) {
같은 생성자니까 순서를 바꾸는 게 맞는 것 같습니다! 놓쳤습니다. 감사합니다!

2023-05-07 04:40 UTC, YGwan commented on src/main/resources/application.yml
> +  sql.init.mode: never
아 알겠습니다!! 확인했습니다!!

2023-05-07 04:42 UTC, YGwan commented on src/main/java/com/ting/ting/exception/TingApplicationException.java
>      public String getMessage() {
아 확인 완료했습니다!!
"client에는 serviceType과 errorCode의 정보가 없는 개발자가 설정한 message만을 넘기도록 변경했습니다."
이 말씀이 이 부분을 의미하는 거였군요!!
제대로 확인했어야됐는대 놓쳤습니다!!

감사합니다!!

2023-05-07 04:44 UTC, solpinetree commented on src/main/java/com/ting/ting/domain/GroupMemberRequest.java
> +    private RequestStatus status = RequestStatus.PENDING;
```java
private RequestStatus status = RequestStatus.PENDING;
```
GroupMemberRequest 인스턴스가 생성될 때, status의 값은 RequestStatus.PENDING 으로  설정해주는 코드입니다! 해당 필드를 생성자에서 안 받도록 하면 개발자가 따로 설정할 필요 없이 새로운 값 insert시에 RequestStatus.PENDING  으로 값이 설정되므로 실수할 여지가 없다고 생각이 되어 더 좋은 접근이 아닌가 생각해왔었습니다!

그리고 처음 값이 들어갈 때는 무조건 PENDING의 값이 들어가므로 자동으로 처리할 수 있는 부분을 직접 처리할 이유가 있나 싶기도 합니다! 어떻게 생각하시나요??

2023-05-07 04:46 UTC, solpinetree commented on src/main/java/com/ting/ting/domain/Group.java
> -
아니에요! 제가 코딩한 부분인 걸요!. 개발하다보면 완벽할 수 없으니까 formatting 관련한 것도 눈에 띄면 계속 수정하겠습니다!

2023-05-07 04:49 UTC, YGwan commented on src/main/java/com/ting/ting/domain/GroupMemberRequest.java
> +    private RequestStatus status = RequestStatus.PENDING;
좋은것 같아요!! 사실 이 부분을 보고 생각을 해봤는대 저는 요청을 할때 직관적으로 PENDING하는 것을 보여주고 싶었는데 요청 테이블에 값이 저장되는거 자체가 PENDING을 의미하는거기 때문에 말씀대로 더 좋은 접근이라고 생각합니다.
추가적으로 `"해당 필드를 생성자에서 안 받도록 하면 개발자가 따로 설정할 필요 없이 새로운 값 insert시에 RequestStatus.PENDING 으로 값이 설정되므로 실수할 여지가 없다고 생각이 되어 더 좋은 접근이 아닌가 생각해왔었습니다!"` 이 말씀도 공감이 됐습니다!
해당 부분 이후에 따로 요청 관련 추가 작업을 할때 변경사항 추가로 커밋해도 될까요??

2023-05-07 04:50 UTC, solpinetree commented on src/main/java/com/ting/ting/dto/response/ResultObject.java
> +        return new ResultObject(HttpStatus.OK.value(), null, "success");
성공, 실패시의 response 틀을 달리하는 것보다 통일성 있게 가는 게 나을 거라고 생각됩니다!

이렇게 수정해도 괜찮을까요??

2023-05-07 04:50 UTC, YGwan commented on src/main/java/com/ting/ting/domain/Group.java
> -
좋아요!! 저도 이런 부분 보면 계속 수정하도록 하겠습니다!!
최종적으로 백엔드 관련 코드가 완료되면 전체적으로 한번 더 살펴봐요!!

2023-05-07 05:05 UTC, solpinetree commented on src/main/java/com/ting/ting/domain/GroupMemberRequest.java
> +    private RequestStatus status = RequestStatus.PENDING;
넵! 좋아요!

2023-05-07 05:35 UTC, YGwan commented on src/main/java/com/ting/ting/dto/response/ResultObject.java
> +        return new ResultObject(HttpStatus.OK.value(), null, "success");
네넵 좋아요!! 저도 통일성 있게 가는게 좋을거 같습니다!!

2023-05-07 05:41 UTC, solpinetree commented
### 피드백 후 수정사항 
---
* ErrorCode enum class에서 getHttpStatus() 메소드를 구현했습니다
      String 타입의 HttpStatus 는 개발자가 에러를 정의하기 위해 set 하는 과정에서만 쓰일 것으로 예상됩니다. 이에 `getHttpStatus()` 메서드는 int형인 status code를 반환하도록 설정했습니다.

* 생성 response에도 serviceType을 명시하도록 수정(`AbstractController` 도입)
    success 할 때마다 `ServiceType` 을 명시해주는 것이 번거로우므로 `AbstractController` 를 도입했습니다. `AbstractController`를 통해 해당 컨트롤러의 `ServiceType`을 Response에 넘기도록 했습니다.

* Service Interface 도입
     주석과 코드의 분리를 위해 Service Interface 를 생성했습니다. 

* `AbstractService` 도입
     에러 던질 때마다 ServiceType을 넘겨 주는 것이 번거로우므로 `AbstractService` 를 통해 해당 서비스의 ServiceType을 넘기도록 했습니다.

--- 
소개팅 관련 비즈니스 로직이 UserService에 포함되어도 되는건지 고민해봐야될 것 같습니다! userRepository에 접근하긴 하지만, 해당 데이터(로직)은 소개팅에 필요해서 사용되는 것이기 때문입니다. 어떻게 생각하시는지 궁금합니다!

2023-05-07 06:32 UTC, YGwan requested changes
오 주석을 interface로 관리하고 abstract class를 통해 불필요한 중복된 코드를 관리하는 작업 너무 괜찮은 것 같습니다!! 너무 잘해주셔서 욕심이 계속 생기네요!!

정말 좋은 접근인거 같습니다!! 저도 코드를 보면서 시아가 넓어지는 느낌을 받았습니다. 수고하셨어요!!

저는 코드를 보면서 두가지 생각이 들었어요!!

첫번째로 주석과 코드를 분리하기 위해 interface를 두신 것을 Controller단에도 적용하는게 어떨까요?? 사실 저희가 주석을 단 이유는 팀 프로젝트를 효율적으로 하기 위한것도 있지만 swagger에서 적용하기 위해서인 것도 있으니깐 사실 가장 중요한 것은 controller의 주석이라는 생각이 들었어요!! 그래서 해당 controller부분도 통일성 있게 다는게 좋다는 생각이 들었습니다.

두번째로, 이제는 controller에서 service 코드에 접근할때 interface를 통해서 접근하더라구요!! 저희는 사실 주석과 코드의 분리를 위해서 interface를 사용했지만 기본적으로 spring에서 interface는 설계와 구현부를 분리하여 OCP를 잘 수행하기 위해서도 사용한 것으로 알고 있습니다! 그런데 보니 지금은 해당 인터페이스를 상속한게 Impl밖에 없기 때문에 문제가 되지 않지만 후에 만약 해당 인터페이스를 상속한 다른 구현 클래스가 생기면 spring측에서 controller단에 어떤 service 구현체를 사용해야하는지 몰라 에러를 발생시키더라구요
이러한 부분을 명시하는 여러가지 방법이 있지만 저는 SpringConfig 클래스를 통해 @Bean으로 관리하는 것을 좋아합니다! 혹시 해당 부분 어떻게 생각하시는지 궁금해요!!

https://velog.io/@falling_star3/Spring-Boot-%EC%8A%A4%ED%94%84%EB%A7%81-%EB%B9%88bean%EA%B3%BC-%EC%9D%98%EC%A1%B4%EA%B4%80%EA%B3%84

관련 자료 첨부드립니다!!

2023-05-07 06:32 UTC, YGwan commented on src/main/java/com/ting/ting/service/UserServiceImpl.java
> +public class UserServiceImpl implements UserService{
혹시 해당 부분 UserService와 {사이에 붙인 이유가 있을까요?? 전체적인 코드를 다 떼신거 같아서 통일하는게 좋다고 생각해요!!

2023-05-07 06:33 UTC, YGwan commented
`소개팅 관련 비즈니스 로직이 UserService에 포함되어도 되는건지 고민해봐야될 것 같습니다! userRepository에 접근하긴 하지만, 해당 데이터(로직)은 소개팅에 필요해서 사용되는 것이기 때문입니다. 어떻게 생각하시는지 궁금합니다!`

혹시 이 말씀이 지금 blindService가 존재하는대 이를 UserService로 통합해서 관리하자는 말씀이신가요??

2023-05-07 08:00 UTC, solpinetree commented
> `소개팅 관련 비즈니스 로직이 UserService에 포함되어도 되는건지 고민해봐야될 것 같습니다! 소개팅 사용자 조회 과정에서 userRepository에 접근하긴 하지만, 해당 데이터(로직)은 소개팅에 필요해서 사용되는 것이기 때문입니다. 어떻게 생각하시는지 궁금합니다!`
> 
> 혹시 이 말씀이 지금 blindService가 존재하는대 이를 UserService로 통합해서 관리하자는 말씀이신가요??

UserService 안에 소개팅 관련 비즈니스 로직이 존재하는 게 맞는 건지에 대해 여쭤본 거 였습니다. UserService에 있는 소개팅 로직이 BlindService로 옮겨져야 하는 게 아닐까요??

2023-05-07 08:01 UTC, solpinetree commented on src/main/java/com/ting/ting/service/UserServiceImpl.java
> +public class UserServiceImpl implements UserService{
네 확인을 못 한 것 같습니다! 수정해서 커밋하겠습니다

2023-05-07 08:31 UTC, YGwan commented
아 맞네요!! 해당 부분도 후에 추가적인 요청 작업 처리할때 반영해서 commit하겠습니다!!

2023-05-07 08:36 UTC, solpinetree commented
> 첫번째로 주석과 코드를 분리하기 위해 interface를 두신 것을 Controller단에도 적용하는게 어떨까요?? 사실 저희가 주석을 단 이유는 팀 프로젝트를 효율적으로 하기 위한것도 있지만 swagger에서 적용하기 위해서인 것도 있으니깐 사실 가장 중요한 것은 controller의 주석이라는 생각이 들었어요!! 그래서 해당 controller부분도 통일성 있게 다는게 좋다는 생각이 들었습니다.

네! controller에도 적용시키는 게 나을 것 같습니다. 해당 부분 수정해서 커밋하겠습니다!

> 두번째로, 이제는 controller에서 service 코드에 접근할때 interface를 통해서 접근하더라구요!! 저희는 사실 주석과 코드의 분리를 위해서 interface를 사용했지만 기본적으로 spring에서 interface는 설계와 구현부를 분리하여 OCP를 잘 수행하기 위해서도 사용한 것으로 알고 있습니다! 그런데 보니 지금은 해당 인터페이스를 상속한게 Impl밖에 없기 때문에 문제가 되지 않지만 후에 만약 해당 인터페이스를 상속한 다른 구현 클래스가 생기면 spring측에서 controller단에 어떤 service 구현체를 사용해야하는지 몰라 에러를 발생시키더라구요 이러한 부분을 명시하는 여러가지 방법이 있지만 저는 SpringConfig 클래스를 통해 @bean으로 관리하는 것을 좋아합니다! 혹시 해당 부분 어떻게 생각하시는지 궁금해요!!

네 맞습니다! 지금 개발이 너무 밀려서 뒤로 미룬 일이었는데요. 해당 부분도 수정해서 커밋하겠습니다!

2023-05-07 12:28 UTC, YGwan approved these changes
수고하셨습니다!!

2023-05-07 13:59 UTC, merged