[과팅] [팀장] 과팅 요청, 취소 기능 구현
realSolarDragons/back-end pull request #85
Opened 2023-05-15 14:07 UTC by solpinetree

*  #83
* #84

#81 에서 branch를 시작했기 때문에 #81에 포함되는 코드도 같이 포함이 되었습니다. 위의 각 pr에서 메세지 확인해주시면 더 이해가 잘 가실 거예요! 감사합니다.

2023-05-16 03:25 UTC, YGwan requested changes
수고하셨습니다!!

[#83](https://github.com/realSolarDragons/back-end/pull/83)
여기서 말씀해주신 `이미 fromGroup이 toGroup에 요청을 보낸 상태는 아닌지(toGroup이 fromGroup에 보냈는지는 확인하지 않습니다. 후에 두 팀 중 어떤 팀이 요청을 수락할 때 서로 요청한 레코드를 모두 삭제하기 떄문입니다.)(밑에 코드 블럭 참고해주세요!)`
이 부분에 처리를 그냥 리셋하신거 같은대 사실 이 부분은 조회가 안되야 되는 부분인대 조회가 된 부분이라 에러 처리하는 로직으로 가는게 더 낫지 않을까요??
조회시 상대방이 나한테 요청을 보낸 이력이 있으면 보이지 않게 하기로 했던거 같아서요!!

수고 많으셨습니다!!

2023-05-16 03:25 UTC, YGwan commented on src/main/java/com/ting/ting/dto/response/GroupDateRequestWithFromAndToResponse.java
> +public class GroupDateRequestWithFromAndToResponse {
그런데 팀에게 온 요청 + 본인 팀이 했던 요청을 한 번에 볼 일이 있을까요??

2023-05-16 03:25 UTC, YGwan commented on src/main/java/com/ting/ting/controller/AdminControllerImpl.java
> +    public Response<Page<GroupResponse>> getGroupList(Pageable pageable) {
이것은 성별에 상관없이 생성된 모든 과팅 그룹을 볼 수 있는 api라고 생각하면 될까요??

2023-05-16 03:25 UTC, YGwan commented on src/main/java/com/ting/ting/domain/Group.java
> +    @Column(name = "is_joinable", nullable = false)
이 컬럼 추가하신 것도 정말 좋은 접근인거 같습니다!!

2023-05-16 03:25 UTC, YGwan commented on src/main/java/com/ting/ting/service/GroupServiceImpl.java
> +    public Page<GroupWithRequestStatusResponse> findSuggestedSameGenderGroupList(Long userId, Pageable pageable) {
sameGender라는 것을 추가해서 어떤 역할의 메서드인지 더 알아보기 쉽군요!!
좋습니다!!

2023-05-16 03:25 UTC, YGwan commented on src/main/java/com/ting/ting/service/GroupServiceImpl.java
> +        if (leader.getGender().equals(Gender.MEN)) {
이 로직을 GroupDateResponse에서 처리하게 하는건 어떤가요??
그렇게 된다면 230번째 줄도 없앨수 있고 해당 로직이 더 잘 보일거 같다는 생각이 들었습니다.
GroupDateResponse에 fromGroup, toGroup를 보내 그 안에서 처리하게 하는 방식으로 하면 더 좋을 것 같아요!!

2023-05-16 03:25 UTC, YGwan commented on src/main/java/com/ting/ting/service/GroupServiceImpl.java
> +            menGroup = fromGroup;
그리고 여기서 만약 DB에 정보가 손상이되어 toGroup과 fromGroup이 다 같이 성별로 저장이 되있으면 그냥 저장이 될거 같은데, 위에 해당 부분을 검증하는 에러 처리 로직이 추가되면 더 좋을 것 같아요!!

2023-05-16 03:39 UTC, solpinetree commented on src/main/java/com/ting/ting/dto/response/GroupDateRequestWithFromAndToResponse.java
> +public class GroupDateRequestWithFromAndToResponse {
>이 부분에 처리를 그냥 리셋하신거 같은대 사실 이 부분은 조회가 안되야 되는 부분인대 조회가 된 부분이라 에러 처리하는 로직으로 가는게 더 낫지 않을까요??
조회시 상대방이 나한테 요청을 보낸 이력이 있으면 보이지 않게 하기로 했던거 같아서요!!

네! 뷰단에선 안 보이도록 할 예정입니다.  만약 `fromGroup` 이 `toGroup`에게 요청을 보내기 직전에 `toGroup` 팀이 이미 다른 팀 조회 페이지에 접속한 경우 `fromGroup` 은 조회 목록에 포함이 되었을 것이고, 요청 버튼도 enable 된 상황일 것을 고려한 로직이었습니다. 조회를 하고 있는 사람은 요청이 온 사실을 몰랐는데 요청이 reject  되면 당황스러울 것 같습니다! client의 문제가 아닌 에러이고 사실 요청은 받아야지 의미가 있는 거라 지금 상황의 에러는 크리티컬 하지 않다고 생각했습니다! 결론적으로는, 에러 처리를 하든 제가 한 방법으로 하든 별 차이는 없을 것 같지만 사용자 경험을 고려했을 때는 에러 처리를 안 하는 방법이 나을 것 같다고 판단됩니다. 어떻게 생각하시나요??

2023-05-16 03:40 UTC, solpinetree commented on src/main/java/com/ting/ting/dto/response/GroupDateRequestWithFromAndToResponse.java
> +public class GroupDateRequestWithFromAndToResponse {
> 그런데 팀에게 온 요청 + 본인 팀이 했던 요청을 한 번에 볼 일이 있을까요??

<img src="https://github.com/realSolarDragons/back-end/assets/83967710/2bf97070-17b8-45a6-9cd3-8c45f11211ce" width="50%" height="50%"/>

해당 피그마 참고 부탁드립니다!

2023-05-16 03:42 UTC, solpinetree commented on src/main/java/com/ting/ting/controller/AdminControllerImpl.java
> +    public Response<Page<GroupResponse>> getGroupList(Pageable pageable) {
네 맞습니다! 지금은 개발용으로 쓰이는 api 입니다. 추후에 admin 도메인이 개발된다며 adminService 단으로 옮길 예정입니다.

2023-05-16 03:50 UTC, solpinetree commented on src/main/java/com/ting/ting/service/GroupServiceImpl.java
> +        if (leader.getGender().equals(Gender.MEN)) {
그렇게 처리하는 게 더 깔끔할 것 같습니다! 하지만, 밑에 코드를 보시면 `group_date` 테이블에서 `menGroup` 과 `womenGroup` 중 하나가 존재하는지 확인하기 위해 서비스 단에서 성별로 나뉘어져야 합니다. 제가 잘 이해한 거 맞을까요? 더 좋은 방법이 있으면 제안해주시면 감사하겠습니다!

2023-05-16 03:51 UTC, solpinetree commented on src/main/java/com/ting/ting/service/GroupServiceImpl.java
> +            menGroup = fromGroup;
`toGroup` 과 `fromGroup` 이 같은 성별일 때의 에러 처리를 말씀하시는 건가요??

2023-05-16 04:13 UTC, YGwan commented on src/main/java/com/ting/ting/service/GroupServiceImpl.java
> +            menGroup = fromGroup;
네넵!! 맞습니다!!

2023-05-16 04:13 UTC, YGwan commented on src/main/java/com/ting/ting/service/GroupServiceImpl.java
> +            menGroup = fromGroup;
할 필요가 없을지 해야할지 몰라서 저도 처음엔 안 넣었었는데 작업하면서 코드를 추가했습니다!!
해당 부분이 필요할까요 안필요할까요?? 좋은 의견 있으시면 알려주시면 감사하겠습니다!!

2023-05-16 04:15 UTC, solpinetree commented on src/main/java/com/ting/ting/service/GroupServiceImpl.java
> +            menGroup = fromGroup;
코드 232번 보면 해당 에러 처리한 부분 있습니다!

2023-05-16 04:15 UTC, solpinetree commented on src/main/java/com/ting/ting/service/GroupServiceImpl.java
> +            menGroup = fromGroup;
저는 필요하다고 생각합니다!

2023-05-16 04:19 UTC, YGwan commented on src/main/java/com/ting/ting/service/GroupServiceImpl.java
> +            menGroup = fromGroup;
아 제가 leader를 통해 접근한걸 보고 헷갈렸네요!!
확인했습니다!!

2023-05-16 04:22 UTC, YGwan commented on src/main/java/com/ting/ting/service/GroupServiceImpl.java
> +        if (leader.getGender().equals(Gender.MEN)) {
아 그러네요!! 저는 해당 작업을 Response에서 처리하게 했는대 과팅 같은 경우는 유일성이 보장되야 되니 해당 부분을 처리하는 로직이 있어야하므로 service단에서 처리해야하네요!!
그렇다면 이 방법이 젤 좋은 것 같습니다!!

2023-05-16 04:30 UTC, YGwan commented on src/main/java/com/ting/ting/dto/response/GroupDateRequestWithFromAndToResponse.java
> +public class GroupDateRequestWithFromAndToResponse {
>네! 뷰단에선 안 보이도록 할 예정입니다. 만약 fromGroup 이 toGroup에게 요청을 보내기 직전에 toGroup 팀이 이미 다른 팀 조회 페이지에 접속한 경우 fromGroup 은 조회 목록에 포함이 되었을 것이고, 요청 버튼도 enable 된 상황일 것을 고려한 로직이었습니다. 조회를 하고 있는 사람은 요청이 온 사실을 몰랐는데 요청이 reject 되면 당황스러울 것 같습니다! client의 문제가 아닌 에러이고 사실 요청은 받아야지 의미가 있는 거라 지금 상황의 에러는 크리티컬 하지 않다고 생각했습니다! 결론적으로는, 에러 처리를 하든 제가 한 방법으로 하든 별 차이는 없을 것 같지만 사용자 경험을 고려했을 때는 에러 처리를 안 하는 방법이 나을 것 같다고 판단됩니다. 어떻게 생각하시나요??

음 그러게요!! 이 상황을 처리할때 문제가 될 수 있겟네요!!
그런데 이렇게 되면 사용자 A와 B가 있을때 사용자 A -> B한테 보냈고 보내기 전, B가 조회를 해서 A 사용자가 보여지고 B -> A에게 요청을 보냈는데 이 상황이 전과 동일하게 계속해서 반복이 되면 무한으로 계속해서 처리가 안되지 않을까요?? 상황을 말로 설명하려니 좀 어렵네요...
그리고 후에 알람을 구현하면 알람이 이미 상대방한테 와 있을텐데 해당 알람이 잘못된 알람으로 되지 않을까요?? 
어떻게 생각하시는지 궁금합니다!!

2023-05-16 04:30 UTC, YGwan commented on src/main/java/com/ting/ting/dto/response/GroupDateRequestWithFromAndToResponse.java
> +public class GroupDateRequestWithFromAndToResponse {
>해당 피그마 참고 부탁드립니다!

아 헉... 저도 그럼 해당 부분을 수정해야겠군요!! 감사합니다!!

2023-05-16 04:46 UTC, solpinetree commented on src/main/java/com/ting/ting/dto/response/GroupDateRequestWithFromAndToResponse.java
> +public class GroupDateRequestWithFromAndToResponse {
> 음 그러게요!! 이 상황을 처리할때 문제가 될 수 있겟네요!! 그런데 이렇게 되면 사용자 A와 B가 있을때 사용자 A -> B한테 보냈고 보내기 전, B가 조회를 해서 A 사용자가 보여지고 B -> A에게 요청을 보냈는데 이 상황이 전과 동일하게 계속해서 반복이 되면 무한으로 계속해서 처리가 안되지 않을까요?? 상황을 말로 설명하려니 좀 어렵네요... 그리고 후에 알람을 구현하면 알람이 이미 상대방한테 와 있을텐데 해당 알람이 잘못된 알람으로 되지 않을까요?? 어떻게 생각하시는지 궁금합니다!!

A -> B 요청
B -> A 요청
=> 페이지 refresh 시에 A, B 두 그룹은 서로 보이지 않게 됩니다. 

A -> B 요청 알람 
B -> A 요청 알람
& 서로 과팅 요청 페이지에서 서로 조회 가능

만약, A가 먼저 요청을 수락한 경우(A->B 요청은 삭제됨). 따라서, B-> A의 요청을 수락해도 처리가 되지 않습니다.
잘못된 알람은 문제가 되지 않을 것 같습니다! 잘못된 알람을 클릭시에 이미 매칭된 과팅입니다라는 안내 메세지를 보여주면 된다고 생각했씁니다. 
혹시 어떤 점에서 가장 걸리시는지 자세히 설명해주실 수 있을까요??

2023-05-16 04:47 UTC, solpinetree commented on src/main/java/com/ting/ting/dto/response/GroupDateRequestWithFromAndToResponse.java
> +public class GroupDateRequestWithFromAndToResponse {
> 아 헉... 저도 그럼 해당 부분을 수정해야겠군요!! 감사합니다!! 후에 따로 이슈 작업으로 처리해도 될까요?? 

넵! 알겠습니다

2023-05-16 05:06 UTC, YGwan commented on src/main/java/com/ting/ting/dto/response/GroupDateRequestWithFromAndToResponse.java
> +public class GroupDateRequestWithFromAndToResponse {
아 제가 잘못 접근했네요... 수락 로직에서는 딱히 문제가 될 것 같지 않습니다!! 죄송합니다...

지금 그럼 과팅이 성공햇을때, 과팅 상대편 조회같은 경우에는 비활성화 시킬 생각이신가요??

2023-05-16 06:02 UTC, solpinetree commented on src/main/java/com/ting/ting/dto/response/GroupDateRequestWithFromAndToResponse.java
> +public class GroupDateRequestWithFromAndToResponse {
> 아 제가 요청 조회 로직이랑 혼동해서 잘못 접근했네요... 수락 로직에서는 딱히 문제가 될 것 같지 않습니다!! 죄송합니다...
> 
> 지금 그럼 과팅이 성공햇을때, 과팅 상대편 조회같은 경우에는 비활성화 시킬 생각이신가요??

그러게요! 그건 기획의 부재라.. 정하기 나름일 것 같습니다! 

지금 드는 생각은 매칭된 과팅이 있는 경우, 상대팀 조회는 비활성화 시키지 않고 요청 버튼만 비활성화 시킨 후에, 찜기능만 활성화 시키는 것입니다. 그렇게 되면 매칭된 과팅 취소하기 기능도 추가되어야할 것 같고요.. 

어떻게 생각하시나요?? 이외에 간단한 방법이 생각나시면 공유해주시면 감사하겠습니다!

2023-05-16 17:35 UTC, YGwan commented
혹시 저 그 요청 수락 관련해서 하나 더 생각해본 결과가 있는데,

일단 말씀대로 사용자의 편의성을 고려하기 위해 에러 처리보다는 다르게 처리하는것은 동의합니다!!

그런데 생각해보니 그렇게 되면 RequestStatus에 accepted는 필요 없게 되고 PENDING, REJECTED만 필요하게 되더라구요!!

거절이 있으면 수락도 있는게 일반적이라고 생각합니다. 또한 요청 테이블에 있는 요청 정보를 수락했는데 요청 테이블에 정보가 사라지는 이러한 흐름이 해석하기 다르겠지만 좀 이상하다 라는 생각도 들었습니다. 
또한 아까 말씀드린 불필요한 Join문 뿐만아니라 후에 만약 소개팅이 끝나고 나면 해당 테이블의 정보는 제거 되어야 합니다.(갯수 제한이 존재하기 때문에) 그렇다면 소개팅이 끝나고 다시 사용자를 조회하게 된다면 조회가 되겠죠. 하지만 해당 정보가 로그처럼 blind_request 테이블에 남아있게 된다면 후에도 조회 처리가 안될 수 있게 처리할 수 있다고 생각합니다!! (과팅도 만약 과팅이 끝난 후에 과팅 팀이 남아있다면 동일하게 처리되겠죠!!)

따라서 제가 생각하기엔 에러로 처리하는 것이 아닌, 만약 fromUser와 toUser가 바뀐 정보가 추가적으로 존재한다면, 해당 정보 또한 ACCEPTED로 바꿔주는 로직으로 처리하는 것이 어떤지 궁금합니다!! 이렇게 되면 조회 로직에 Date 테이블까지 조인할 필요도 없고 과팅 / 소개팅이 끝나면 해당 정보가 로그처럼 남아있을 수도 있어 더 좋을 것 같다는 생각이 들었습니다. 이것에 대한 간단한 코드 첨부합니다!!

```
blindRequest.setStatus(RequestStatus.ACCEPTED);
blindRequestRepository.save(blindRequest);

Optional<BlindRequest> oppositeCase = blindRequestRepository.findByFromUserAndToUser(touser, fromUser);

oppositeCase.ifPresent(otherBlindRequest -> {
    otherBlindRequest.setStatus(RequestStatus.ACCEPTED);
    blindRequestRepository.save(otherBlindRequest);
});
```

2023-05-17 01:52 UTC, solpinetree commented
> 거절이 있으면 수락도 있는게 일반적이라고 생각합니다. 또한 요청 테이블에 있는 요청 정보를 수락했는데 요청 테이블에 정보가 사라지는 이러한 흐름이 해석하기 다르겠지만 좀 이상하다 라는 생각도 들었습니다.
또한 아까 말씀드린 불필요한 Join문 뿐만아니라 후에 만약 소개팅이 끝나고 나면 해당 테이블의 정보는 제거 되어야 합니다.(갯수 제한이 존재하기 때문에) 그렇다면 소개팅이 끝나고 다시 사용자를 조회하게 된다면 조회가 되겠죠. 하지만 해당 정보가 로그처럼 blind_request 테이블에 남아있게 된다면 후에도 조회 처리가 안될 수 있게 처리할 수 있다고 생각합니다!! (과팅도 만약 과팅이 끝난 후에 과팅 팀이 남아있다면 동일하게 처리되겠죠!!)

소개팅이 끝나고 다시 소개팅 매칭 되었던 사용자가 조회 안 되도록 해야한다고 생각하고 있지 않았습니다! .. 꼭 그렇게 해야 하는지 의문입니다. 기획을 어떻게 하냐에 따라 다를 것 같습니다. 처음에는 사용자가 많이 없기 때문에 매칭 되었던 사람들도 보여주는 게 나을 것 같다고 생각됩니다. 

이 외에도, 이미 매칭된 사람도 포함하여 검색 결과를 보고 싶은 사용자들도 있을 것 같습니다. 소개팅 후에 특정 시간이 지나서 다시 그 사람과 대화를 하고 싶은 경우도 있을 것 같습니다. 그래서, 매칭 되었던 사용자가 조회 안 되도록 하는 건 후에 필터 기능으로 제공하는 건 어떨까요??

2023-05-17 05:05 UTC, YGwan approved these changes
수고하셨습니다!!

2023-05-17 05:15 UTC, merged