[소개팅] 소개팅 조회 로직, 소개팅 성공시 저장 로직 추가
realSolarDragons/back-end pull request #89
Opened 2023-05-15 19:50 UTC by YGwan

1. 소개팅 조회 로직 ( 이 부분 같이 얘기해보고 싶습니다!!)
  - 저는 총 두가지 방법으로 했는데 둘 다 올려놓았고 후에 정해지면 둘중 하나의 방식으로 할 예정입니다.
  - 첫번째 방법 - join문 사용
       - join문을 통해서 소개팅 상대를 조회하는 방식입니다.
       - `@Query`를 통해 구현합니다.
       - 비교적 코드가 간단하고 깔끔합니다.
       - 하지만, 조회시 전체 user를 대상으로 조회해야하는 문제가 있습니다.
       - 후에 찜하기 관련 테이블이 생성될 경우 이에 대한 join까지 진행하여 총 3개의 테이블에 대한 join이 필요합니다.
    
  - 두번째 방법 - list를 통한 전체 순회
     - pagenation을 통한 총 20개의 유저를 전체 순회하면서 상태값을 확인하는 방식으로 처리됩니다.
     - join문이 필요가 없습니다.
     - 전체 유저를 다 보는 것이 아닌 20개의 유저만 봅니다.
     - DB 커넥션이 많다는 단점이 있습니다.
     - 코드가 비교적 길어집니다.

이렇게 총 두가지 방법이 있습니다. 과팅의 경우 과팅 생성된 것을 기반으로 하기 때문에 엄청 그렇게 많은 데이터를 볼 필요는 없을 수도 있습니다. 하지만 저 같은 경우 상대방의 유저 전체를 다 확인해야한다면 후에 만약 사용자가 많아지면 문제가 생길 것이라고 생각해 이렇게 두가지 방식을 생각해보았습니다. 간단하게 한번 더 요약하자면, 첫번째 방법은 join문을 통한 방법으로 누나가 하신 방법과 동일합니다. 두번째 방법은 service단에서 상대 유저 20명을 전체 순회 하면서, 해당 형식을 맞춰주는 방식입니다. 둘 다 장단점이 있다고 생각하는데 어떻게 생각하시는지 궁금합니다!!

3. 소개팅 성공시 저장 로직 추가

소개팅이 성공하면 해당 성공 정보를 저장하는 별도의 테이블을 생성하였습니다.

2023-05-16 05:54 UTC, solpinetree requested changes
코드 잘 봤습니다! 말씀하신대로 두가지 방법 둘 다 장단점이 있는 것 같습니다. 
지금 소개팅 조회 로직에서는 2번이 더 적합하다고 생각이 듭니다! 
소개팅은 DB에서 데이터를 가져와서 그 데이터와 연관된 필요한 데이터를 combining 하는 과정이 복잡하지 않고(join 문을 대신할 추가과정이 복잡하지 않고), 말씀하신대로 user의 수가 많기 때문입니다. 

저도 계속 고민 중인데 지금으로서 그리고 출시하고도 당분간은 둘의 방법이 크게 차이가 나진 않을 것 같습니다. 물론 저도 찜하기 기능을 구현하게 된다면 jpql에서 join으로만 값을 가져오기엔 한계가 있다고 생각합니다!

2023-05-16 05:54 UTC, solpinetree commented on src/main/java/com/ting/ting/controller/BlindDateController.java
> +    Response<Set<BlindUserWithRequestStatusResponse>> blindUsersInfo(@ParameterObject Pageable pageable);
여기서 반환인자를 `Page` 에서 `Set`으로 바꾸신 이유가 있으실까요?? 페이지네이션 사용하면, 페이지네이션에 대한 정보를 프론트가 알아야 다음 페이지네이션에 대한 요청을 하는 것 아닌가 해서요!

2023-05-16 05:54 UTC, solpinetree commented on src/main/java/com/ting/ting/service/BlindServiceImpl.java
> +            Optional<BlindRequest> blindRequestUserInfo = blindRequestRepository.findByFromUserAndToUser(user, otherUser);
여기서 `findByFromUser(user)` 로 api를 사용 중인 유저가 보낸 요청에 대한 `toUser` 를 리스트로 가져온 후에
```java
Set<User> toUsers = userRepository.findByFromUser(user);
```

``` java
for(User otherUser : otherUsers) {
     BlindUserWithRequestStatusResponse response = new BlindUserWithRequestStatus();
     response.setUser = otherUser;
     if(toUsers.contains(otherUser) {
        response.setStatus = "PENDING";
     } else {
        response.setStatus = null;
     }
    blindUserWithRequestStatusResponse.add(response);
}
```

이런식으로 하는 게 낫지 않을까요??? 여기서 작성한 코드는 blindRequestUserInfo.get().getStatus() 값이 "PENDING" 만 있을 거란 예상 하에 적은 코드입니다. 제가 잘못 이해한 거라면 말해주세요!!

소개팅 요청을 pagination 없이 다 가져온다는 점에서 각각 `findByFromUserAndToUser(user, otherUser);` 에서 가져오는 방법을 채택하신 것 같습니다! 하지만, 한 사람이 보내는 요청의 수가 그렇게 고려할 정도로 많지 않을 것 같습니다. 많다고 가정해도 한 api 콜에서 최대 20번의 db select 문을 날리는 것보다는 나을 것 같습니다
어떻게 생각하시는지 궁금합니다!!

2023-05-16 15:15 UTC, YGwan commented on src/main/java/com/ting/ting/controller/BlindDateController.java
> +    Response<Set<BlindUserWithRequestStatusResponse>> blindUsersInfo(@ParameterObject Pageable pageable);
아 그러네요!!  이 부분 수정하도록 하겠습니다!!

2023-05-16 15:33 UTC, YGwan commented on src/main/java/com/ting/ting/controller/BlindDateController.java
> +    Response<Set<BlindUserWithRequestStatusResponse>> blindUsersInfo(@ParameterObject Pageable pageable);
이 부분 수정했습니다. 그런데 제가 한 로직이 제대로 동작하는건지 잘 모르겟어서 혹시 봐주시고 문제 있으면 알려주시면 감사하겠습니다!!

일단 getMapping상은 문제가 없습니다!!

2023-05-16 16:57 UTC, YGwan commented on src/main/java/com/ting/ting/service/BlindServiceImpl.java
> +            Optional<BlindRequest> blindRequestUserInfo = blindRequestRepository.findByFromUserAndToUser(user, otherUser);
와 정말 좋은 접근인거 같아요... 저는 이 부분을 진짜 많이 고민하고 낸 결론인대
이런식으로 처리하면 db connection문제도 어느정도 해결되고 코드도 더 깔끔해지네요.
이러한 형식으로 변경해서 구현 완료 했습니다.

정말 좋은 접근인거 같습니다!! 감사합니다!!!

2023-05-17 06:24 UTC, solpinetree requested changes
오늘 수업에서 얘기하기 전에 찾았던 오타가 있어서 먼저 공유드립니다!

2023-05-18 07:11 UTC, YGwan commented on src/main/java/com/ting/ting/repository/BlindRequestRepository.java
> +    Set<BlindRequest> findAllByFromUserAndStatusIsNot(User FromUser, RequestStatus status);
감사합니다!! 수정완료했습니다!!

2023-05-18 09:33 UTC, YGwan commented
수정 완료했습니다.

추가로, 최대 소개팅 요청 수 5개, 소개팅 성공한 횟수 3개로 조정하였습니다!

2023-05-19 01:36 UTC, solpinetree reviewed
수정된 커밋이 없는데 다시 확인 부탁드립니다!!

2023-05-19 02:28 UTC, YGwan commented
아 push를 안했군요.. 다시 했습니다!!!

2023-05-19 03:04 UTC, solpinetree reviewed
수정하시느라 고생하셨습니다!! 👍👍 혹시 소개팅 요청 횟수 제한 로직은 아직 구현이 안된 거 맞나요?!

2023-05-19 03:11 UTC, YGwan commented
```
        if (blindRequestRepository.countByFromUserAndStatus(fromUser, RequestStatus.PENDING) >= 5) {
            throwException(ErrorCode.LIMIT_NUMBER_OF_REQUEST);
        }

        if(blindDateRepository.countByBlindDate(fromUser) >= 3) {
            throwException(ErrorCode.LIMIT_NUMBER_OF_BlIND_DATE);
        }

```

위의 코드가 소개팅 요청에 대한 5개의 제한 관련 코드이고

아래가 소개팅 성공에 대한 3개의 제한 관련 코드입니다.

소개팅 요청의 경우 상대방이 나에게 요청을 보낸 횟수와는 무관하게 내가 보낸 요청의 수만 가지고 판단하였습니다!!

혹시 더 좋은 방법이 있으면 알려주시면 감사하겠습니다!!

2023-05-19 03:13 UTC, solpinetree approved these changes
아 그 위의 코드를 제가 확인을 못했네요!! 고생하셨습니다~~

2023-05-19 03:37 UTC, merged